[general]
live_config_reload = true

[font]
normal = { family = "Comic Code", style = "Regular" }
size = 24

[colors.primary]
background = "#2d0f03"
foreground = "#d3c6aa"

[window]
option_as_alt = "OnlyLeft"
