theme = "everforest_dark"

[keys.normal.t]
k = "expand_selection"
j = "shrink_selection"
h = "select_prev_sibling"
l = "select_next_sibling"

[editor]
line-number = "relative"
mouse = false

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"
# other-lines = "error"
