add_newline = false
palette = 'mcm'
format = '''
$directory > 
'''

[directory]
truncate_to_repo = false
style = 'bold earthy'

[os]
disabled = false

[shell]
disabled = false
style = 'bold text'

[time]
disabled = false
style = 'green'

[palettes.mcm]
green = '#61795e'
orange = '#ae2c02'
yellow = '#c27815'
earthy = '#d5a25d'
red = '#7f1903'
text = '#d3c6aa'
faded = '#574f3e'
