add_newline = true
palette = 'mcm'
format = '''
$directory
$os
'''

[directory]
truncate_to_repo = false
style = 'text'

[os]
disabled = false

[shell]
disabled = false

[time]
disabled = false
style = 'green'

[palettes.mcm]
green = '#61795e'
orange = '#ae2c02'
yellow = '#c27815'
red = '#7f1903'
text = '#d3c6aa'
